# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben Galewsky
email: bengal1@illinois.edu

#write html inside the double quotes to display in jumbotron
description: "<h1>Development Blog</h1><h3>Research Programmer NCSA</h3>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bengalewsky.github.io" # the base hostname & protocol for your site
github_username:  bengalewsky

# Build settings
markdown: kramdown
